language: java

jdk:
  - oraclejdk7

env: JAVA_6_HOME=/usr/lib/jvm/java-6-openjdk-amd64 JAVA_7_HOME=/usr/lib/jvm/java-7-oracle JAVA_8_HOME=/usr/lib/jvm/java-8-oracle

script: mvn test | grep -Fv 'DEBUG'
